name: My_First_Name
on: push
jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4
            - name: Welcome message
              run: echo "Welcome Dipanshu"
            - name: List File
              run: ls
            - name: Read File
              run: cat README.md
        
        