name: Workflow2
on: push
jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4
            - name: Echo Message
              run: echo "Hello World"
            - name: List File
              run: ls -latr
            - name: Cat file
              run: cat README.md